spring:
  datasource:
    url: jdbc:h2:tcp://localhost/file:D:/Tool/h2_db/community
    username: sa
    password: 1
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create #이미 있으면 drop하고 create함
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace